[versions]
agp = "9.0.0"
androidxCore = "1.13.1"
androidxAppcompat = "1.7.0"
androidxFragment = "1.8.5"
androidxActivity = "1.9.3"
androidxAnnotation = "1.9.1"
androidxSplashscreen = "1.0.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "androidxFragment" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashscreen" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
